// Generated by CoffeeScript 1.4.0
(function() {
  var JustGiving, https, parse, _;

  https = require('https');

  parse = require('url').parse;

  _ = require('underscore')._;

  JustGiving = (function() {

    JustGiving.DirectDonatePath = '/donation/direct/charity';

    JustGiving.GetDonationDetails = "/v1/donation/";

    function JustGiving(siteUrl, apiUrl, apiKey) {
      this.siteUrl = siteUrl;
      this.apiUrl = apiUrl;
      this.apiKey = apiKey;
    }

    JustGiving.prototype.getDonationUrl = function(charityId, callbackUrl, ourData, thirdPartyReference, amount) {
      var url;
      url = this.siteUrl + JustGiving.DirectDonatePath;
      url += "/" + charityId + "?frequency=single";
      if (amount != null) {
        url += "&amount=" + amount;
      }
      if (thirdPartyReference != null) {
        url += "&reference=" + encodeURIComponent(thirdPartyReference);
      }
      url += "&exitUrl=" + encodeURIComponent(callbackUrl + ("?id=JUSTGIVING-DONATION-ID&data=" + (encodeURIComponent(ourData))));
      return url;
    };

    JustGiving.prototype.getDonationStatus = function(donationId, callback) {
      var buf, opts, url;
      url = this.apiUrl + JustGiving.GetDonationDetails + donationId;
      buf = '';
      opts = {
        headers: {
          'Accept': 'application/json',
          'x-api-key': this.apiKey
        }
      };
      return https.get(_.extend(parse(url), opts), function(res) {
        console.log("getDonationStatus() for " + donationId + " responded with " + res.statusCode);
        res.on('data', function(data) {
          return buf += data;
        });
        return res.on('end', function() {
          return callback(null, JSON.parse(buf));
        });
      }).on('error', function(e) {
        return callback(e);
      });
    };

    return JustGiving;

  })();

  module.exports = JustGiving;

}).call(this);
