// Generated by CoffeeScript 1.4.0
(function() {
  var JustGiving;

  JustGiving = (function() {

    JustGiving.DirectDonatePath = '/donation/direct/charity';

    function JustGiving(siteUrl, apiUrl, apiKey) {
      this.siteUrl = siteUrl;
      this.apiUrl = apiUrl;
      this.apiKey = apiKey;
    }

    JustGiving.prototype.getDonationUrl = function(charityId, callbackUrl, ourReference, amount) {
      var url;
      url = this.siteUrl + JustGiving.DirectDonatePath;
      url += "/" + charityId + "/donate?frequency=single";
      if (amount) {
        url += "&amount=" + amount;
      }
      url += "&exitUrl=" + encodeURIComponent(callbackUrl + ("?donationId=JUSTGIVING-DONATION-ID&id=" + ourReference));
      return url;
    };

    JustGiving.prototype.getDonationStatus = function(donationId) {
      var url;
      return url = this.apiUrl + ("/api/" + this.apiKey + "/v1/donation/" + donationId);
    };

    return JustGiving;

  })();

  module.exports = JustGiving;

}).call(this);
