// Generated by CoffeeScript 1.4.0
(function() {
  var urls, wrap;

  wrap = function(fnString) {
    return "(" + fnString + ")";
  };

  urls = {
    recent_charities: wrap((function() {
      return "/json/recent_charities";
    }).toString()),
    typeahead_charities: wrap((function() {
      return "/json/typeahead_charities";
    }).toString()),
    justgiving_charity: wrap((function() {
      return app.env.justgiving.apiUrl + '/' + app.env.justgiving.apiKey + "/v1/charity";
    }).toString()),
    justgiving_charity_search: wrap((function(query, pageSize, page) {
      if (pageSize == null) {
        pageSize = 8;
      }
      if (page == null) {
        page = 1;
      }
      return app.env.justgiving.apiUrl + '/' + app.env.justgiving.apiKey + "/v1/charity/search" + "?q=" + query + "&pageSize=" + pageSize + "&page=" + page;
    }).toString())
  };

  module.exports = function(app, config) {
    console.log("Defining API routes");
    return app.get("/json/client_init", function(req, res) {
      return res.json({
        authed: req.user != null,
        env: {
          justgiving: _.pick(config.justgiving, 'apiKey', 'apiUrl')
        },
        urls: urls
      });
    });
  };

}).call(this);
