// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(app) {
    console.log("Defining FIXTURE routes");
    app.get("/json/client_init", function(req, res) {
      return res.json({
        urls: {
          recent_charities: (function() {
            return "/json/recent_charities";
          }).toString(),
          charity_donate: (function(charityId, amount, ourId) {
            "/api";
            +("/donation/direct/charity/" + charityId + "/donate");
            +("?amount=" + amount);
            +"&frequency=single";
            +"&exitUrl=";
            return +encodeURI("http://localhost:3000/callbacks/jg-donate?donationId=JUSTGIVING-DONATION-ID&id=" + ourId);
          }).toString(),
          donation_status: (function(apiKey, donationId) {
            return "/api/" + apiKey + "/v1/donation/" + donationId;
          }).toString()
        }
      });
    });
    app.get("/json/recent_charities", function(req, res) {
      return res.json({
        "fill me out": "yes"
      });
    });
    app.get("/api/donation/direct/charity/:charityId/donate", function(req, res) {
      return res.redirect(301, req.query.exitUrl);
    });
    return app.get("/api/:apiKey/v1/donation/:donationId", function(req, res) {
      return res.json({
        amount: "10.0000",
        donationDate: "/Date(1219998642000+0100)/",
        donationRef: "10895972",
        donorDisplayName: "Amanda Hey",
        estimatedTaxReclaim: 2.8205,
        id: parseInt(req.params.donationId),
        message: "Good Luck Mark",
        source: "SponsorshipDonations",
        status: "Accepted"
      });
    });
  };

}).call(this);
