// Generated by CoffeeScript 1.4.0
(function() {
  var urls, wrap;

  wrap = function(fnString) {
    return "(" + fnString + ")";
  };

  urls = {
    recent_charities: wrap((function() {
      return "/json/recent_charities";
    }).toString()),
    typeahead_charities: wrap((function() {
      return "/json/typeahead_charities";
    }).toString()),
    charity_donate: wrap((function(charityId, amount, ourId) {
      "/api";
      +("/donation/direct/charity/" + charityId + "/donate");
      +("?amount=" + amount);
      +"&frequency=single";
      +"&exitUrl=";
      return +encodeURI("http://localhost:3000/callbacks/jg-donate?donationId=JUSTGIVING-DONATION-ID&id=" + ourId);
    }).toString()),
    donation_status: wrap((function(apiKey, donationId) {
      return "/api/" + apiKey + "/v1/donation/" + donationId;
    }).toString())
  };

  module.exports = function(app) {
    console.log("Defining FIXTURE routes");
    app.get("/json/client_init", function(req, res) {
      return res.json({
        authed: req.user != null,
        urls: urls
      });
    });
    app.get("/api/donation/direct/charity/:charityId/donate", function(req, res) {
      return res.redirect(301, req.query.exitUrl);
    });
    return app.get("/api/:apiKey/v1/donation/:donationId", function(req, res) {
      return res.json({
        amount: "10.0000",
        donationDate: "/Date(1219998642000+0100)/",
        donationRef: "10895972",
        donorDisplayName: "Amanda Hey",
        estimatedTaxReclaim: 2.8205,
        id: parseInt(req.params.donationId),
        message: "Good Luck Mark",
        source: "SponsorshipDonations",
        status: "Accepted"
      });
    });
  };

}).call(this);
