// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    sessionSecret: 'fortytwo',
    couchdb: {
      url: 'http://admin:admin@dev.lightmytree.org',
      port: 5984
    },
    dbs: {
      users: 'lmt_users',
      trees: 'lmt_trees'
    },
    twitter: {
      consumerKey: 'Ev4MopNlRrygyAYDCEkFUg',
      consumerSecret: '5DPw6SeeIChXriFOf0AT38O5pJWi0vfg8NChQvWY'
    }
  };

}).call(this);
