// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    sessionSecret: 'devmode',
    couchdb: {
      url: 'http://admin:admin@dev.lightmytree.org',
      port: 5984
    },
    dbs: {
      users: 'lmt_users',
      trees: 'lmt_trees'
    },
    justgiving: {
      apiKey: 'e90e23e0',
      apiUrl: 'https://api-sandbox.justgiving.com',
      siteUrl: 'https://v3-sandbox.justgiving.com',
      callbackUrl: 'http://dev.lightmytree.org:3000/callback/jg'
    },
    twitter: {
      consumerKey: 'Ev4MopNlRrygyAYDCEkFUg',
      consumerSecret: '5DPw6SeeIChXriFOf0AT38O5pJWi0vfg8NChQvWY'
    }
  };

}).call(this);
